title: Breeze
email: support@swissuplabs.com
description: >-
  Breeze â€” is a minimalistic Magento starter theme for your next unique design.
baseurl: ""
url: "https://breezefront.com"
github_username: swissup

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections_dir: collections
collections:
  landings:
    output: true
    permalink: /:name
  getting-started:
    output: true
    permalink: /docs/:name
    navigation: true
    title: Getting Started
    order: 10
  core-concepts:
    output: true
    permalink: /docs/:name
    navigation: true
    title: Core Concepts
    order: 20
  js:
    output: true
    permalink: /docs/:name
    navigation: true
    title: JS
    order: 30
  guides:
    output: true
    permalink: /docs/:name
    navigation: true
    title: Guides
    order: 40
  theming:
    output: true
    permalink: /docs/:name
    navigation: true
    title: Theming
    order: 50
  components:
    output: true
    permalink: /docs/:name
    navigation: true
    title: Components
    order: 60

markdown: kramdown
kramdown:
  toc_levels: 2..5

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
